### ISSUE TITLE
Python 2.6 support ?

### ISSUE THREAD

**Issue by thefab** [andreasjansson/envtpl#12]
Hi,

We are very interested in your library because we built a similar tool based on django template engine. 

But now, in a docker world, we prefer a minimal library with fewer dependencies.

BUT, we need Python 2.6 compatibility because of RedHat / CentOS 6.x linux distribution we mainly use.

Are you interested in this support in your "official" repo ? Or do you prefer we fork it ?

Regards

Fabien

**Comment by andreasjansson** [comment]
Hi @thefab, happy to hear you want to use it! I have nothing against Python 2.6 support per se. The code itself is just a couple hundred lines, so shouldn't be that hard to make compatible, provided that there aren't dependencies that rely on >2.7. If you can get it to work I'd be happy to merge it into master. But if it turns out to be harder, feel free to keep a fork around, and I can link to it from this repo.

There's also a go port https://github.com/mattrobenolt/envtpl, not sure how maintained it is though.

**Comment by thefab** [comment]
great, we are going to provide a pull request about this
